version: '3.8'

services:

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: always
    networks:
      - searxng
      - reverse-proxy
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - "${SEARXNG_ETC_DIR}:/etc/searxng:rw"
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    internal: true
    ipam:
      driver: default
  reverse-proxy:
    external: true
    name: "${REVERSE_PROXY_NETWORK}"
  external-net:
