version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - "3001"
    volumes:
      - "${UPTIME_KUMA_DATA_DIR}:/app/data"
    networks:
      - reverse-proxy-net
      - postgres-net
      - mariadb-net

networks:
  reverse-proxy-net:
    external: true
    name: ${REVERSE_PROXY_NETWORK}
  postgres-net:
    external: true
    name: ${POSTGRES_NETWORK}
  mariadb-net:
    external: true
    name: ${MARIADB_NETWORK}
  email-relay-net:
    external: true
    name: "${EMAIL_RELAY_NETWORK}"
